import { Activity, Participation, UserProfile } from "../types";

export const mockUser: UserProfile = {
  uid: 'student-1',
  email: 'student@example.com',
  displayName: 'John Doe',
  role: 'student',
  studentId: 'STU2023001',
  department: 'Computer Science',
  year: '3rd Year',
  createdAt: Date.now(),
};

export const mockCoordinator: UserProfile = {
  uid: 'coord-1',
  email: 'coordinator@example.com',
  displayName: 'Prof. Sarah Smith',
  role: 'coordinator',
  createdAt: Date.now(),
};

export const mockActivities: Activity[] = [
  {
    id: 'act-1',
    title: 'Inter-College Tech Fest',
    description: 'A grand competition of coding, hacking, and innovative projects.',
    type: 'competition',
    status: 'upcoming',
    date: Date.now() + 86400000 * 5,
    location: 'Main Auditorium',
    coordinatorId: 'coord-1',
    coordinatorName: 'Prof. Sarah Smith',
    currentParticipants: 45,
    maxParticipants: 100,
    tags: ['coding', 'innovation', 'tech'],
    createdAt: Date.now(),
  },
  {
    id: 'act-2',
    title: 'Football Championship',
    description: 'Annual inter-departmental football tournament.',
    type: 'sport',
    status: 'ongoing',
    date: Date.now() + 86400000,
    location: 'Sports Ground',
    coordinatorId: 'coord-1',
    coordinatorName: 'Prof. Sarah Smith',
    currentParticipants: 80,
    maxParticipants: 120,
    tags: ['sports', 'teamwork'],
    createdAt: Date.now(),
  },
  {
    id: 'act-3',
    title: 'Debate Club Weekly Meet',
    description: 'Discussing current affairs and global challenges.',
    type: 'club',
    status: 'upcoming',
    date: Date.now() + 86400000 * 2,
    location: 'Meeting Room B',
    coordinatorId: 'coord-1',
    coordinatorName: 'Prof. Sarah Smith',
    currentParticipants: 15,
    maxParticipants: 30,
    tags: ['debate', 'soft-skills'],
    createdAt: Date.now(),
  },
  {
    id: 'act-4',
    title: 'Creative Writing Workshop',
    description: 'Hone your writing skills with professional authors.',
    type: 'event',
    status: 'upcoming',
    date: Date.now() + 86400000 * 3,
    location: 'Open Air Theatre',
    coordinatorId: 'coord-1',
    coordinatorName: 'Prof. Sarah Smith',
    currentParticipants: 12,
    maxParticipants: 50,
    tags: ['creative', 'writing'],
    createdAt: Date.now(),
  },
  {
    id: 'act-5',
    title: 'Basketball Friendly Match',
    description: 'Staff vs Students friendly basketball game.',
    type: 'sport',
    status: 'upcoming',
    date: Date.now() + 86400000 * 1,
    location: 'Indoor Gym',
    coordinatorId: 'coord-1',
    coordinatorName: 'Prof. Sarah Smith',
    currentParticipants: 22,
    maxParticipants: 30,
    tags: ['sport', 'community'],
    createdAt: Date.now(),
  },
  {
    id: 'act-6',
    title: 'Digital Marketing Seminar',
    description: 'Learn the latest trends in social media and SEO.',
    type: 'event',
    status: 'upcoming',
    date: Date.now() + 86400000 * 7,
    location: 'Seminar Hall 1',
    coordinatorId: 'coord-1',
    coordinatorName: 'Prof. Sarah Smith',
    currentParticipants: 10,
    maxParticipants: 80,
    tags: ['marketing', 'digital'],
    createdAt: Date.now(),
  },
  {
    id: 'act-7',
    title: 'Yoga & Wellness Session',
    description: 'A relaxing morning of yoga and mindfulness.',
    type: 'event',
    status: 'upcoming',
    date: Date.now() + 86400000 * 2,
    location: 'Campus Garden',
    coordinatorId: 'coord-1',
    coordinatorName: 'Prof. Sarah Smith',
    currentParticipants: 15,
    maxParticipants: 40,
    tags: ['wellness', 'yoga'],
    createdAt: Date.now(),
  },
  {
    id: 'act-8',
    title: 'Robotics Workshop',
    description: 'Build and program your own mini-robot.',
    type: 'competition',
    status: 'upcoming',
    date: Date.now() + 86400000 * 10,
    location: 'Lab 402',
    coordinatorId: 'coord-1',
    coordinatorName: 'Prof. Sarah Smith',
    currentParticipants: 5,
    maxParticipants: 20,
    tags: ['tech', 'robotics'],
    createdAt: Date.now(),
  },
  {
    id: 'act-9',
    title: 'Art Exhibition',
    description: 'Annual showcase of student artwork and photography.',
    type: 'event',
    status: 'upcoming',
    date: Date.now() + 86400000 * 14,
    location: 'Exhibition Hall',
    coordinatorId: 'coord-1',
    coordinatorName: 'Prof. Sarah Smith',
    currentParticipants: 0,
    maxParticipants: 200,
    tags: ['art', 'exhibition'],
    createdAt: Date.now(),
  },
  {
    id: 'act-10',
    title: 'Table Tennis Finals',
    description: 'The final showdown of the semester tournament.',
    type: 'sport',
    status: 'upcoming',
    date: Date.now() + 86400000 * 6,
    location: 'Indoor Stadium',
    coordinatorId: 'coord-1',
    coordinatorName: 'Prof. Sarah Smith',
    currentParticipants: 8,
    maxParticipants: 16,
    tags: ['sport', 'competition'],
    createdAt: Date.now(),
  },
  {
    id: 'act-11',
    title: 'Movie Night: Sci-Fi Edition',
    description: 'Join us for a screening of Interstellar with free popcorn.',
    type: 'club',
    status: 'upcoming',
    date: Date.now() + 86400000 * 4,
    location: 'Cinema Room',
    coordinatorId: 'coord-1',
    coordinatorName: 'Prof. Sarah Smith',
    currentParticipants: 45,
    maxParticipants: 60,
    tags: ['movie', 'social'],
    createdAt: Date.now(),
  }
];

export const mockParticipations: Participation[] = [
  {
    id: 'p-1',
    studentId: 'student-1',
    studentName: 'John Doe',
    studentEmail: 'student@example.com',
    activityId: 'act-1',
    activityTitle: 'Inter-College Tech Fest',
    activityDate: Date.now() + 86400000 * 5,
    activityType: 'competition',
    status: 'registered',
    registeredAt: Date.now() - 86400000,
  },
  {
    id: 'p-2',
    studentId: 'student-1',
    studentName: 'John Doe',
    studentEmail: 'student@example.com',
    activityId: 'act-2',
    activityTitle: 'Football Championship',
    activityDate: Date.now() + 86400000,
    activityType: 'sport',
    status: 'registered',
    registeredAt: Date.now() - 86400000 * 2,
  }
];
